my:
  default:
    value: my-defaul-value

---
spring:
  profiles: configuration-client
  application:
    name: configuration-client
---
spring:
  profiles: configuration-service
  application:
    name: configuration-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/bcntec-learning/spring-2019/05-configuration/data/{application}
server:
  port: 8888